#!/bin/python3

import sys
n = int(input().strip())
unsorted = []
for i in range(n):
   unsorte = str(input().strip())
   unsorted.append(unsorte)
unsorted.sort(key=int)
for i in unsorted:
    print(i)
